### ISSUE TITLE
 panic: exec: "": executable file not found in $PATH

### ISSUE THREAD

**Issue by minitoaster** [mumoshu/helm-x#36]
Hi !

I'm trying to use helm x with helmfile and I have a problem

I'm using Helm 3.5 on macOs. Everything was installed with brew

I installed helm-x with

`helm plugin install https://github.com/mumoshu/helm-x` 

But when I'm trying to run helmfile with option --helm-binary /Users/myuser/Library/helm/plugins/helm-x/bin/helm-x

I got the following error
`
STDERR:
  panic: exec: "": executable file not found in $PATH
  goroutine 1 [running]:
  github.com/mumoshu/helm-x/pkg/helmx.(*Runner).IsHelm3(0xc0000d29c0, 0x8)
  	/home/circleci/project/pkg/helmx/helm3.go:21 +0x19a
  main.main()
  	/home/circleci/project/main.go:32 +0x73
`
Can you help me please ?

**Comment by krrrr38** [comment]
A workaround is adding `HELM_BIN` environment variable explicitly like `HELM_BIN=$(which helm) helmfile --helm-binary /path/to/bin/helm-x apply`.
